name: 🚨 Report an issue
description: Report an issue.
body:
  - type: checkboxes
    attributes:
      label: Support guidelines
      description: Please read the support guidelines before proceeding.
      options:
        - label: I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the issue in 1-2 sentences.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: Please describe precisely what you'd expect to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behaviour
      description: Please describe precisely what is actually happening.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version
      description: Please provide the HASS version, component version and system information (ARM, Docker, anything usefull).
      value: |
        * HASS version:
        * Component version:
        * Useful system info:
    validations:
      required: true

  - type: textarea
    attributes:
      label: HASS logs
      description: Please provide the HASS logs (preferably with debug enabled).
      value: |
        * logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml
    validations:
      required: true
